### ISSUE TITLE
when i try to run bot.Contact.find,get some error.

### ISSUE THREAD

**Issue by fangjiyuan** [wechaty/python-wechaty-puppet-itchat#16]
2021-09-28 16:42:08,275 - RoomBot - ERROR - should ready()<sync> the ContactSelf payload before get it, please call the <ready()> method
Traceback (most recent call last):
  File "d:\github\python-wechaty-puppet-itchat\examples\hotreload_bot.py", line 140, in send_report
    contact = await bot.Contact.find(query=ContactQueryFilter(name=str3))
  File "D:\ProgramData\Anaconda3\envs\py37\lib\site-packages\wechaty\user\contact.py", line 110, in find
    contact_list = await cls.find_all(query)
  File "D:\ProgramData\Anaconda3\envs\py37\lib\site-packages\wechaty\user\contact.py", line 158, in find_all
    contacts
  File "D:\ProgramData\Anaconda3\envs\py37\lib\site-packages\wechaty\user\contact.py", line 152, in <lambda>
    lambda x: x.payload and (
  File "D:\ProgramData\Anaconda3\envs\py37\lib\site-packages\wechaty\accessory.py", line 80, in payload
    type(self).__name__
ValueError: should ready()<sync> the ContactSelf payload before get it, please call the <ready()> method

**Comment by lyleshaw** [comment]
Please update `python-wechaty-puppet-itchat` to the latest version to support the `Contact.find` function.

And note that due to the limitations of `UOS-WeChat`, `python-wechaty-puppet-itchat` cannot obtain the weixin_id of the contact, so you can only search for the contact by `UOS-WeChat` contact name (such as `@46213ce0c1ad615c6fb330047c777e29cb19b5363047c777e29cb19b53305c`)

**Comment by fangjiyuan** [comment]
> Please update `python-wechaty-puppet-itchat` to the latest version to support the `Contact.find` function.
> 
> And note that due to the limitations of `UOS-WeChat`, `python-wechaty-puppet-itchat` cannot obtain the weixin_id of the contact, so you can only search for the contact by `UOS-WeChat` contact name (such as `@46213ce0c1ad615c6fb330047c777e29cb19b5363047c777e29cb19b53305c`)

我已经更新了最新版本的python-wechaty-puppet-itchat，还是无法使用Contact.find，提示和一楼一样。
